### ISSUE TITLE
How to add NiFi 2 support

### ISSUE THREAD

**Issue by lfdominguez** [galbash/otel-nifi-extension#1]
Hi, how can I check if this work for the new Nifi 2.0.0, I tried and otel agent its working but dont see any of my processors on my traces, only get Nifi http traces and postgresql connection.
I add only the extension, need to add some config or this detect all processors?

**Comment by galbash** [comment]
Hi @lfdominguez, thanks for your interest! This is currently only tested for 1.22.x versions, but contributions are welcome!
The main idea is the hook around the session operations (put, get, create etc) and to match each one with a corresponding span. To adapt this to version 2 I suggest first checking if these objects and mechanisms remained the same. I won't be very available this month (October) but happy to help later on if this is still relevant

**Comment by lfdominguez** [comment]
Sorry, already found that updating the dependencies of the project to version 2 works great, thanks!!!
